Get the swig wrappers linked and installed. Still more work on installing to the right location and to get the .py files installed.
* Makefile.in:
  - add dirs for installing the swig-related bits (swig_pydir,
    swig_javadir, swig_java_libdir); these need more work, especially
    to be set from configure.
  - add SWIG_PY_LINK for linking Python extensions.
  - add SWIG_LDFLAGS for the flags needed to link against the SWIG
    runtime libraries (usually a -L to specify where those libs are).
  - shift the special libtool flags to LINK_APACHE_MOD so we can toss
    the link-flags stuff from the system.
  - add LINK_*_WRAPPER symbols for linking the wrappers
  - add INSTALL_SWIG_* for installing the various swig bits

* ac-helpers/get-py-info.py: add --link switch for figuring out how to
    link Python extensions.

* ac-helpers/swig.m4: add code for setting up SWIG_PY_LINK

* build.conf: toss 'link-flags' because we specify that in the
    Makefile now. add libraries to the swig wrappers.

* build/gen_base.py:
  (GeneratorBase.__init__): don't worry about setting up .ldflags
    because we specify the custom flags in the Makefile now. refactor
    how we locate the libraries specified in the "libs" option line
    into _find_libs and use it for adding intra-library dependencies.
    also use it for finding libs we need to add to the swig wrappers.
  (GeneratorBase._find_libs): refactored code for mapping "libs"
    options into dependent objects.
  (SWIGLibrary.ldflags): removed; no longer needed.
  (TargetSWIG.add_dependencies): add the dependent libraries. add some
    hacky code for adding some language-specific libraries.
  (_cfg_defaults): no need to provide a 'link-flags' default

* build/gen_make.py:
  (MakefileGenerator.write): remove the use of .ldflags


git-svn-id: https://svn.apache.org/repos/asf/subversion/trunk@844340 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -47,6 +47,11 @@ srcdir = @srcdir@
 infodir = @infodir@
 
 swig_py_libdir= @libdir@
+swig_java_libdir= @libdir@
+
+### this isn't right
+swig_pydir = @libdir@/svn-python/svn
+swig_javadir = @libdir@/svn-java
 
 ### should search for these...
 MAKEINFO = @MAKEINFO@
@@ -73,8 +78,10 @@ SWIG = @SWIG@
 SWIG_INCLUDES = -I$(SWIG_SRC_DIR) \
                 -I$(abs_srcdir)/subversion/include \
                 $(SVN_APR_INCLUDES)
+SWIG_LDFLAGS = @SWIG_LDFLAGS@
 SWIG_PY_INCLUDES = @SWIG_PY_INCLUDES@
 SWIG_PY_COMPILE = @SWIG_PY_COMPILE@
+SWIG_PY_LINK = @SWIG_PY_LINK@
 SWIG_PY_SETUP_LDFLAGS = @SWIG_PY_SETUP_LDFLAGS@
 SWIG_JAVA_INCLUDES = @SWIG_JAVA_INCLUDES@
 
@@ -98,7 +105,7 @@ COMPILE_SWIG_PY = $(LIBTOOL) $(LTFLAGS) --mode=compile $(CC) $(CPPFLAGS) -DSWIGP
 COMPILE_SWIG_JAVA = $(LIBTOOL) $(LTFLAGS) --mode=compile $(CC) $(CPPFLAGS) -DSWIGPYTHON $(CFLAGS) $(SWIG_JAVA_INCLUDES) $(INCLUDES) -o $@ -c $<
 
 LINK = $(LIBTOOL) $(LTFLAGS) --mode=link $(CC) $(LT_LDFLAGS) $(CFLAGS) $(LDFLAGS) -rpath $(libdir)
-LINK_APACHE_MOD = $(LIBTOOL) $(LTFLAGS) --mode=link $(CC) $(LT_LDFLAGS) $(CFLAGS) $(LDFLAGS) -rpath $(APACHE_LIBEXECDIR)
+LINK_APACHE_MOD = $(LIBTOOL) $(LTFLAGS) --mode=link $(CC) $(LT_LDFLAGS) $(CFLAGS) $(LDFLAGS) -rpath $(APACHE_LIBEXECDIR) -avoid-version -module
 
 RUN_SWIG_PY = $(SWIG) -c -python -noproxy $(SWIG_INCLUDES) $(SWIG_PY_INCLUDES) -o $@ $<
 RUN_SWIG_JAVA = $(SWIG) -c -java -noproxy -module 'Subversion' -package 'org.tigris.subversion.swig' $(SWIG_INCLUDES) -o $@ $<
@@ -106,6 +113,10 @@ RUN_SWIG_JAVA = $(SWIG) -c -java -noproxy -module 'Subversion' -package 'org.tig
 COMPILE_PY_WRAPPER = $(LIBTOOL) $(LTFLAGS) --mode=compile $(SWIG_PY_COMPILE) $(SWIG_INCLUDES) $(SWIG_PY_INCLUDES) -prefer-pic -c -o $@ $<
 COMPILE_JAVA_WRAPPER = \
   echo "ERROR: compilation of Java wrappers not yet supported" ; exit 1
+
+LINK_PY_WRAPPER = $(LIBTOOL) $(LTFLAGS) --mode=link $(SWIG_PY_LINK) $(SWIG_LDFLAGS) -rpath $(swig_pydir) -avoid-version -module
+LINK_JAVA_WRAPPER = \
+  echo "ERROR: linking of Java wrappers not yet supported" ; exit 1
 
 
 INSTALL = @INSTALL@
@@ -119,7 +130,11 @@ INSTALL_MOD_SHARED = @APXS@ -i -S LIBEXECDIR="$(APACHE_LIBEXECDIR)" @MOD_ACTIVAT
 INSTALL_MOD_STATIC = $(INSTALL) -m 644
 INSTALL_DATA = $(INSTALL) -m 644
 
+### this isn't correct yet
+INSTALL_SWIG_PY = $(INSTALL_LIB)
 INSTALL_SWIG_PY_LIB = $(INSTALL_LIB)
+INSTALL_SWIG_JAVA = $(INSTALL_LIB)
+INSTALL_SWIG_JAVA_LIB = $(INSTALL_LIB)
 
 APXS = @APXS@ 
 
