UNIX buildsystem Python detection tweaks.
* Makefile.in (check): Don't bother to check Python version here, configure
    will now reject old Python. Update the error message to highlight that the
    Python detection is configure's responsibility.
    Exit non-zero if "make check" invoked, but we are unable to run the tests
    because of lack of Python.
* configure.in (Python tests): Redesign, inline the functionality of pycheck.py
    here, and make the error message more detailed. Avoid using two variables, 
    $PYTHON and $PYTHON2, preferring $PYTHON, but add a compatibility clause
    so that old buildscripts using PYTHON2=/path/to/python will still work.
* subversion/bindings/swig/INSTALL: Now recommend PYTHON=/path/to/python
    instead of PYTHON2=/path/to/python.
* build/pycheck.py: Delete, no longer required.


git-svn-id: https://svn.apache.org/repos/asf/subversion/trunk@852826 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -348,7 +348,6 @@ check-swig-java: swig-java-tests
 #  will perform only basic tests (likewise for other tests).
 check: $(TEST_DEPS) @BDB_TEST_DEPS@
 	@if test "$(PYTHON)" != "none"; then                                 \
-	  $(PYTHON) $(top_srcdir)/build/pycheck.py;                          \
 	  flags="--verbose";                                                 \
 	  if test "$(CLEANUP)" != ""; then                                   \
 	    flags="--cleanup $$flags";                                       \
@@ -363,8 +362,9 @@ check: $(TEST_DEPS) @BDB_TEST_DEPS@
 		    '$(abs_srcdir)' '$(abs_builddir)' '$(PYTHON)' '$(SHELL)' \
 		    $(TESTS);                                                \
 	else                                                                 \
-	  echo "make check: Python not found";                               \
-	  echo "Please install Python 2.0 or greater";                       \
+	  echo "make check: Python 2.0 or greater is required,";             \
+	  echo "            but was not detected during configure";          \
+	  exit 1;                                                            \
 	fi;
 
 # First, set up Apache as documented in
