Locking branch:  weekly merge of (trunk, r12684:12758) to branch.
One conflict had to be resolved:  kfogel created new code in fs_fs.c
that called path_rev(), but in the branch that function has been
renamed to svn_fs_fs__path_rev().

Oh yeah... and merging the svn:eol-style=native change into the
win32-innosetup files caused entire files to be in "conflict".  But I
guess that's a known bug, right?


git-svn-id: https://svn.apache.org/repos/asf/subversion/branches/locking@852833 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -118,6 +118,7 @@ SWIG_INCLUDES = -I$(SWIG_SRC_DIR) \
                 -I$(abs_srcdir)/subversion/include \
                 -I$(SWIG_LIBSWIG_DIR) \
                 -DSVN_SWIG_VERSION=$(SWIG_VERSION) \
+                -DSWIG_TABLE_TYPE=subversion \
                 $(SVN_APR_INCLUDES) $(SVN_APRUTIL_INCLUDES)
 SWIG_NORUNTIME_FLAG = @SWIG_NORUNTIME_FLAG@
 SWIG_LDFLAGS = @SWIG_LDFLAGS@
@@ -129,6 +130,8 @@ SWIG_JAVA_INCLUDES = @SWIG_JAVA_INCLUDES@ -I$(SWIG_SRC_DIR)/java/libsvn_swig_jav
 SWIG_JAVA_COMPILE = @SWIG_JAVA_COMPILE@
 SWIG_JAVA_LINK = @SWIG_JAVA_LINK@
 SWIG_PL_INCLUDES = @SWIG_PL_INCLUDES@
+LSWIGPL = @LSWIGPL@
+LSWIGPY = @LSWIGPY@
 
 JAVAHL_INCLUDES= @JNI_INCLUDES@ -I$(abs_builddir)/subversion/bindings/java/javahl/include
 
@@ -345,7 +348,6 @@ check-swig-java: swig-java-tests
 #  will perform only basic tests (likewise for other tests).
 check: $(TEST_DEPS) @BDB_TEST_DEPS@
 	@if test "$(PYTHON)" != "none"; then                                 \
-	  $(PYTHON) $(top_srcdir)/build/pycheck.py;                          \
 	  flags="--verbose";                                                 \
 	  if test "$(CLEANUP)" != ""; then                                   \
 	    flags="--cleanup $$flags";                                       \
@@ -360,8 +362,9 @@ check: $(TEST_DEPS) @BDB_TEST_DEPS@
 		    '$(abs_srcdir)' '$(abs_builddir)' '$(PYTHON)' '$(SHELL)' \
 		    $(TESTS);                                                \
 	else                                                                 \
-	  echo "make check: Python not found";                               \
-	  echo "Please install Python 2.0 or greater";                       \
+	  echo "make check: Python 2.0 or greater is required,";             \
+	  echo "            but was not detected during configure";          \
+	  exit 1;                                                            \
 	fi;
 
 # First, set up Apache as documented in
