Merges the 4156:4322 changes from trunk into the issue-1003-dev branch.
git-svn-id: https://svn.apache.org/repos/asf/subversion/branches/issue-1003-dev@844398 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -47,6 +47,11 @@ srcdir = @srcdir@
 infodir = @infodir@
 
 swig_py_libdir= @libdir@
+swig_java_libdir= @libdir@
+
+### this isn't right
+swig_pydir = @libdir@/svn-python/svn
+swig_javadir = @libdir@/svn-java
 
 ### should search for these...
 MAKEINFO = @MAKEINFO@
@@ -70,7 +75,13 @@ APACHE_TARGET = @APACHE_TARGET@
 APACHE_LIBEXECDIR = $(DESTDIR)@APACHE_LIBEXECDIR@
 
 SWIG = @SWIG@
+SWIG_INCLUDES = -I$(SWIG_SRC_DIR) \
+                -I$(abs_srcdir)/subversion/include \
+                $(SVN_APR_INCLUDES)
+SWIG_LDFLAGS = @SWIG_LDFLAGS@
 SWIG_PY_INCLUDES = @SWIG_PY_INCLUDES@
+SWIG_PY_COMPILE = @SWIG_PY_COMPILE@
+SWIG_PY_LINK = @SWIG_PY_LINK@
 SWIG_PY_SETUP_LDFLAGS = @SWIG_PY_SETUP_LDFLAGS@
 SWIG_JAVA_INCLUDES = @SWIG_JAVA_INCLUDES@
 
@@ -94,7 +105,19 @@ COMPILE_SWIG_PY = $(LIBTOOL) $(LTFLAGS) --mode=compile $(CC) $(CPPFLAGS) -DSWIGP
 COMPILE_SWIG_JAVA = $(LIBTOOL) $(LTFLAGS) --mode=compile $(CC) $(CPPFLAGS) -DSWIGPYTHON $(CFLAGS) $(SWIG_JAVA_INCLUDES) $(INCLUDES) -o $@ -c $<
 
 LINK = $(LIBTOOL) $(LTFLAGS) --mode=link $(CC) $(LT_LDFLAGS) $(CFLAGS) $(LDFLAGS) -rpath $(libdir)
-LINK_APACHE_MOD = $(LIBTOOL) $(LTFLAGS) --mode=link $(CC) $(LT_LDFLAGS) $(CFLAGS) $(LDFLAGS) -rpath $(APACHE_LIBEXECDIR)
+LINK_APACHE_MOD = $(LIBTOOL) $(LTFLAGS) --mode=link $(CC) $(LT_LDFLAGS) $(CFLAGS) $(LDFLAGS) -rpath $(APACHE_LIBEXECDIR) -avoid-version -module
+
+RUN_SWIG_PY = $(SWIG) -c -python -noproxy $(SWIG_INCLUDES) $(SWIG_PY_INCLUDES) -o $@ $<
+RUN_SWIG_JAVA = $(SWIG) -c -java -noproxy -module 'Subversion' -package 'org.tigris.subversion.swig' $(SWIG_INCLUDES) -o $@ $<
+
+COMPILE_PY_WRAPPER = $(LIBTOOL) $(LTFLAGS) --mode=compile $(SWIG_PY_COMPILE) $(SWIG_INCLUDES) $(SWIG_PY_INCLUDES) -prefer-pic -c -o $@ $<
+COMPILE_JAVA_WRAPPER = \
+  echo "ERROR: compilation of Java wrappers not yet supported" ; exit 1
+
+LINK_PY_WRAPPER = $(LIBTOOL) $(LTFLAGS) --mode=link $(SWIG_PY_LINK) $(SWIG_LDFLAGS) -rpath $(swig_pydir) -avoid-version -module
+LINK_JAVA_WRAPPER = \
+  echo "ERROR: linking of Java wrappers not yet supported" ; exit 1
+
 
 INSTALL = @INSTALL@
 INSTALL_LIB = $(LIBTOOL) --mode=install $(INSTALL)
@@ -107,7 +130,11 @@ INSTALL_MOD_SHARED = @APXS@ -i -S LIBEXECDIR="$(APACHE_LIBEXECDIR)" @MOD_ACTIVAT
 INSTALL_MOD_STATIC = $(INSTALL) -m 644
 INSTALL_DATA = $(INSTALL) -m 644
 
+### this isn't correct yet
+INSTALL_SWIG_PY = $(INSTALL_LIB)
 INSTALL_SWIG_PY_LIB = $(INSTALL_LIB)
+INSTALL_SWIG_JAVA = $(INSTALL_LIB)
+INSTALL_SWIG_JAVA_LIB = $(INSTALL_LIB)
 
 APXS = @APXS@ 
 
@@ -313,7 +340,7 @@ swig-py-ext: swig-assert-available
 
 install-swig-py-ext: swig-assert-available
 	cd $(SWIG_BUILD_DIR)/python; \
-        $(PYTHON) $(PYTHON_DISTUTIL) install $(DISTUTIL_PARAM)
+        $(PYTHON) $(PYTHON_DISTUTIL) install $(DISTUTIL_PARAM) --prefix=$(DESTDIR)$(prefix)
 
 swig-py-ext-clean:
 	rm -rf $(SWIG_BUILD_DIR)/python/build
