Made 'make check' work even when there's no test listed in SVN_TESTS, the for-line puked when it got an empty list of tests PR: Obtained from: Submitted by: Reviewed by:
git-svn-id: https://svn.apache.org/repos/asf/subversion/trunk@837935 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/subversion/tests/libsvn_ra_dav/Makefile.am b/subversion/tests/libsvn_ra_dav/Makefile.am
--- a/subversion/tests/libsvn_ra_dav/Makefile.am
+++ b/subversion/tests/libsvn_ra_dav/Makefile.am
@@ -28,18 +28,21 @@ SVN_TESTS =
 ## inflexible;  we want better control over automated-test output. 
 check:
 	@echo > tests.log
-	@for prog in $(SVN_TESTS); do \
-	  echo; \
-	  echo -n "Running all sub-tests in $$prog..."; \
-	  ./$$prog >> tests.log; \
-	  if [ $$? -eq 0 ]; \
-	  then \
-	     echo "SUCCESS"; \
-	  else \
-	     echo; \
-	     echo "at least one sub-test FAILED, check tests.log:"; echo; \
-	     cat tests.log | grep FAIL; \
-	  fi; \
-	done
+	@if test -n "$(SVN_TESTS)"; then \
+	  for prog in "$(SVN_TESTS)"; do \
+	    echo; \
+	    echo -n "Running all sub-tests in $$prog..."; \
+	    ./$$prog >> tests.log; \
+	    if [ $$? -eq 0 ]; \
+	    then \
+	       echo "SUCCESS"; \
+	    else \
+	       echo; \
+	       echo "at least one sub-test FAILED, check tests.log:"; echo; \
+	       cat tests.log | grep FAIL; \
+	    fi; \
+	  done \
+	fi
+
 
 
