Bash completion about possible usernames from: - environment variable SVN_BASH_USERNAME - ~/.subversion/auth/... files   (if activated by adding 'username' to SVN_BASH_COMPL_EXT). Costly completions are not activated by default.
* tools/client-side/bash_completion:
  _svn_read_hashfile(): new function to "parse" svn hash files
  _svn(): --username option values handling


git-svn-id: https://svn.apache.org/repos/asf/subversion/trunk@867069 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/tools/client-side/bash_completion b/tools/client-side/bash_completion
--- a/tools/client-side/bash_completion
+++ b/tools/client-side/bash_completion
@@ -10,7 +10,34 @@
 
 shopt -s extglob
 
-# Two helper functions which only use bash, to ease readability.
+# Tree helper functions which only use bash, to ease readability.
+
+# look for value associated to key from stdin in K/V hash file format
+# val=$(_svn_read_hashfile svn:realmstring < some/file)
+function _svn_read_hashfile()
+{
+  local tkey=$1 key= val=
+  while true; do  
+    read tag len
+    [ $tag = 'END' ] && break
+    [ $tag != 'K' ] && {
+      #echo "unexpected tag '$tag' instead of 'K'" >&2
+      return
+    }
+    read -r -n $len key ; read 
+    read tag len
+    [ $tag != 'V' ] && {
+      #echo "unexpected tag '$tag' instead of 'V'" >&2
+      return
+    }
+    read -r -n $len val ; read
+    if [[ $key = $tkey ]] ; then
+      echo "$val"
+      return
+    fi
+  done 
+  #echo "target key '$tkey' not found" >&2
+}
 
 # _svn_grcut shell-regular-expression
 # extract filenames from 'svn status' output
@@ -67,22 +94,23 @@ function _svn_lls()
 #   SVN_BASH_ENCODINGS: encodings to be suggested
 #   SVN_BASH_MIME_TYPE: mime types to be suggested
 #   SVN_BASH_KEYWORDS: "svn:keywords" substitutions to be suggested
+#   SVN_BASH_USERNAME: usernames suggested for --username
 #   SVN_BASH_COMPL_EXT: completion extensions for file arguments, based on the
 #      current subcommand, so that for instance only modified files are 
 #      suggested for 'revert', only not svn-managed files for 'add', and so on.
 #      Possible values are:
+#      - username: guess usernames from ~/.subversion/auth/...
 #      - svnstatus: use 'svn status' for completion
 #      - recurse: allow recursion (expensive)
 #      - externals: recurse into externals (very expensive)
-#     The former option is reasonable, but beware that both later options 
+#     Both former options are reasonable, but beware that both later options 
 #     may be unadvisable if used on large working copies.
 #     None of these costly completions are activated by default.
 #     Argument completion outside a working copy results in an error message.
 #     Filenames with spaces are not completed properly.
 #     
-# - to do: other options? SVN_BASH_USERNAME?
+# - to do: other options? 
 #   obsolete options could be removed from auto-comp? (e.g. -N)
-#   could try to parse ~/.subversion/auth/... to get logins/...
 _svn()
 {
 	local cur cmds cmdOpts pOpts mOpts rOpts qOpts nOpts optsParam opt
@@ -332,8 +360,22 @@ _svn()
 		fi
 	    }
 
-	    # could look at ~/.subversion/
-	    [[ $previous = '--username' ]] && beep=1
+	    if [[ $previous = '--username' ]] ; then
+	      values="$SVN_BASH_USERNAME"
+	      if [[ $SVN_BASH_COMPL_EXT == *username* ]] ; then
+		local file=
+		# digest? others?
+		for file in ~/.subversion/auth/svn.simple/* ; do
+		  if [ -r $file ] ; then
+		    values="$values $(_svn_read_hashfile username < $file)"
+		  fi
+		done
+	      fi
+	      [[ ! "$values" ]] && beep=1
+	    fi
+
+	    # could look at ~/.subversion/ ?
+	    # hmmm... this option should not exist
 	    [[ $previous = '--password' ]] && beep=1
 
 	    # TODO: provide help about other options such as: 
@@ -521,7 +563,7 @@ _svn()
 			files=$cur*
 			;;
 		    ci|commit|revert|di*) # anything edited
-			files=$($status $cs| _svn_grcut '@([MADR!]*| M*)')
+			files=$($status $cs| _svn_grcut '@([MADR!]*| M*|_M*)')
 			;;
 		    add) # unknown files
 			files=$($status $cs| _svn_grcut '\?*')
@@ -565,7 +607,7 @@ _svn()
 		    ls|list) # better job? what about URLs?
 			files=$( _svn_lls all $cur* )
 			;;
-		    *) # other commands: changelist export import cat
+		    *) # other commands: changelist export import cat mergeinfo
 			local fallback=1
 			;;
 		esac
