Convert hashdump-test to new testing system
git-svn-id: https://svn.apache.org/repos/asf/subversion/trunk@837051 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/subversion/libsvn_subr/tests/Makefile.am b/subversion/libsvn_subr/tests/Makefile.am
--- a/subversion/libsvn_subr/tests/Makefile.am
+++ b/subversion/libsvn_subr/tests/Makefile.am
@@ -13,8 +13,27 @@ hashdump_test_LDADD = ../libsvn_subr.la \
                       ../../../apr/libapr.a
 
 
-## Automatic test scripts to run for `make check`
+## Automatic tests run by `make check` -----------------------------
 
-TESTS = hashdump-test.sh
+## A list of test-programs to run.  (Each program contains sub-tests.)
+SVN_TEST_PROGRAMS = hashdump-test
+
+## We're overriding automake's own `check' rule, because it's extremely
+## inflexible;  we want better control over automated-test output. 
+check:
+	@echo > tests.log
+	@for prog in $(SVN_TEST_PROGRAMS); do \
+	  echo; \
+	  echo -n "Running all sub-tests in $$prog..."; \
+	  ./$$prog >> tests.log; \
+	  if [ $$? -eq 0 ]; \
+	  then \
+	     echo "SUCCESS"; \
+	  else \
+	     echo; \
+	     echo "at least one sub-test FAILED, check tests.log:"; echo; \
+	     cat tests.log | grep FAIL; \
+	  fi; \
+	done
 
 
