* contrib/server-side/fsfsfixer/fix-repo   For portability and scalability, iterate over revisions using Bash   arithmetic rather than by calling "seq". Large revision numbers were being   formatted like "2.123456e+06" on some platforms, presumably by "seq",   which caused fix-rev.py to fail. This change should also avoid running   into a command-line length limitation when iterating over a very large   range of revision numbers.
git-svn-id: https://svn.apache.org/repos/asf/subversion/trunk@1092659 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/contrib/server-side/fsfsfixer/fix-repo b/contrib/server-side/fsfsfixer/fix-repo
--- a/contrib/server-side/fsfsfixer/fix-repo
+++ b/contrib/server-side/fsfsfixer/fix-repo
@@ -11,11 +11,16 @@ if [ ! -d "$REPO_DIR" ] || [ "$START_REV" = "" ]; then
   exit 1
 fi
 
-YOUNGEST="$(svnlook youngest $REPO_DIR)"
+YOUNGEST="$(svnlook youngest "$REPO_DIR")"
+
+if [ "$YOUNGEST" = "" ]; then
+  echo "$0: error running 'svnlook youngest $REPO_DIR'"
+  exit 1
+fi
 
 echo "Verifying revisions $START_REV through $YOUNGEST."
 
-for REV in $(seq $START_REV $YOUNGEST); do
-  echo === r$REV
-  ./fixer/fix-rev.py "$REPO_DIR" $REV
+for ((REV=$START_REV; REV <= $YOUNGEST; REV++)); do
+  echo "=== r$REV"
+  ./fixer/fix-rev.py "$REPO_DIR" "$REV"
 done
