Merge r15230:15671 from /branches/1.2.x to /branches/ebcdic/1.2.x
git-svn-id: https://svn.apache.org/repos/asf/subversion/branches/ebcdic@855753 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/1.2.x/contrib/client-side/svnmerge b/1.2.x/contrib/client-side/svnmerge
--- a/1.2.x/contrib/client-side/svnmerge
+++ b/1.2.x/contrib/client-side/svnmerge
@@ -139,7 +139,8 @@ check_branch_dir()
     report "checking status of \"${BRANCH_DIR}\""
     "${SVN_MERGE_SVN}" status -u "${BRANCH_DIR}" | grep -q '^.......\*' && \
         error "\"${BRANCH_DIR}\" is not up to date; please \"svn update\" first"
-    [ `"${SVN_MERGE_SVN}" stat -q "${BRANCH_DIR}" | wc -l` = "0" ] || \
+    [ `"${SVN_MERGE_SVN}" stat -q "${BRANCH_DIR}" \
+      | sed '/^$/,$d' | wc -l` = "0" ] || \
         error "\"${BRANCH_DIR}\" has local modifications; it must be clean"
 }
 
@@ -164,6 +165,12 @@ get_start_end()
     END=`echo "$1" | sed 's/^\([0-9]\{1,\}\)-\([0-9]\{1,\}\)$/\2/g'`
 }
 
+# Subroutine to get all integrated revisions for a given head
+get_all_integrated_revs()
+{
+    RETURN_VALUE=`"${SVN_MERGE_SVN}" propget "${SVN_MERGE_PROP}" "$1"`
+}
+
 # Subroutine to retrieve a target's integrated revisions for a given head
 get_integrated_revs()
 {
@@ -184,7 +191,13 @@ set_integrated_revs()
 # Subroutine to retrieve the default head of the given target
 get_default_head()
 {
-    RETURN_VALUE=`"${SVN_MERGE_SVN}" propget "${SVN_MERGE_PROP}" "$1" | cut -d: -f 1`
+    # To make bi-directional merges easier, find the target's
+    # repository local path so it can be removed from the list of
+    # possible integration sources.
+    target_to_url "$1"
+    url_to_rlpath "${RETURN_VALUE}"
+
+    RETURN_VALUE=`"${SVN_MERGE_SVN}" propget "${SVN_MERGE_PROP}" "$1" | cut -d: -f 1 | grep -v "^${RETURN_VALUE}$"`
     [ -z "${RETURN_VALUE}" ] && error no integration info available
     [ `echo "${RETURN_VALUE}" | wc -l` -gt 1 ] && \
         error explicit \"src\" argument required
@@ -364,7 +377,7 @@ get_copyfrom()
     url_to_rlpath "${RETURN_VALUE}"
     TEMP=`"${SVN_MERGE_SVN}" log -v --xml --stop-on-copy "$1" | tr '\n' ' '`
     TEMP2=`echo "${TEMP}" | sed -e 's#^.*\(<path .*action="A".*>'"${RETURN_VALUE}"'</path>\).*$#\1#'`
-    if [ "${TEMP}" == "${TEMP2}" ]; then
+    if [ "${TEMP}" = "${TEMP2}" ]; then
         RETURN_VALUE=""
     else
         RETURN_VALUE=`echo "${TEMP2}" | sed -e 's/^.* copyfrom-path="\([^"]*\)".*$/\1/'`
@@ -469,6 +482,10 @@ merge()
     beautify_list "${REVS}"
     BREVS="${RETURN_VALUE}"
 
+    # Save "svnmerge-integrated" property value from before the merge
+    get_all_integrated_revs
+    OLDREVS="${RETURN_VALUE}"
+
     # Show what we're doing
     beautify_list "${MERGED_REVS}"
     report "\"${BRANCH_DIR}\" already contains revisions ${RETURN_VALUE}"
@@ -481,6 +498,10 @@ merge()
         svn_command merge -r `expr ${START} - 1`:${END} \
           "${HEAD_URL}" "${BRANCH_DIR}"
     done
+
+    # Revert any merged-in changes to the "svnmerge-integrated" property.
+    # We only want updates to this property to happen via explicit action.
+    svn_command propset -q "${SVN_MERGE_PROP}" "${OLDREVS}" "${BRANCH_DIR}"
 
     # Write out commit message if desired
     if [ "${SVN_MERGE_COMMIT_FILE}" != "" ]; then
@@ -504,12 +525,12 @@ case "$1" in
         BRANCH_DIR="."
         ;;
     avail)
-        FLAGS="svldr:H:"
+        FLAGS="svldr:S:"
         BRANCH_DIR="."
         AVAIL_DISPLAY="revisions"
         ;;
     merge)
-        FLAGS="svnr:f:H:"
+        FLAGS="svnr:f:S:"
         BRANCH_DIR="."
         ;;
     help)
@@ -649,9 +670,26 @@ if TEMP=`"${SVN_MERGE_SVN}" proplist "${BRANCH_DIR}" | grep -Ew "svnmerge-(.+-)?
     exit 1
 fi
 
+# Previous svnmerge versions allowed trailing /'s in the repository
+# local path.  Newer versions of svnmerge will trim trailing /'s
+# appearing in the command line, so if there are any properties with
+# trailing /'s, they will not be properly matched later on, so require
+# the user to change them now.
+if TEMP=`"${SVN_MERGE_SVN}" propget "${SVN_MERGE_PROP}" "${BRANCH_DIR}" | grep -E '/+:[-,0-9]+$'`; then
+    echo "${NAME}: old property values detected; an upgrade is required."
+    echo ''
+    echo 'Please execute and commit these changes to upgrade:'
+    echo ''
+    echo "svn propget ${SVN_MERGE_PROP} ${BRANCH_DIR} > svnmerge1.txt"
+    echo "sed -e 's/\/*\(:[-,0-9]*\)/\1/g' < svnmerge1.txt > svnmerge2.txt"
+    echo "svn propset ${SVN_MERGE_PROP} ${BRANCH_DIR} -F svnmerge2.txt"
+    echo "rm svnmerge1.txt svnmerge2.txt"
+    exit 1
+fi
+
 # Calculate ${HEAD_URL} and ${HEAD_PATH}
 if [ -z "${HEAD}" ]; then
-    if [ "${ACTION}" == "init" ]; then
+    if [ "${ACTION}" = "init" ]; then
         get_copyfrom "${BRANCH_DIR}"
         [ -z "${RETURN_VALUE}" ] && \
             error no copyfrom info available.  Explicit \"src\" argument required.
@@ -664,6 +702,13 @@ if [ -z "${HEAD}" ]; then
     get_repo_root "${BRANCH_DIR}"
     HEAD_URL="${RETURN_VALUE}/${HEAD_PATH}"
 else
+    # The source was given as a command line argument and is stored in
+    # HEAD.  Ensure that the specified source does not end in a /,
+    # otherwise it's easy to have the same source path listed more
+    # than once in the integrated version properties, with and without
+    # trailing /'s.
+    HEAD=`echo ${HEAD} | sed -e 's/\/*$//'`
+
     target_to_url "${HEAD}"
     HEAD_URL="${RETURN_VALUE}"
     url_to_rlpath "${HEAD_URL}"
@@ -688,8 +733,7 @@ fi
 # Get latest revision of head
 report checking latest revision of "${HEAD_URL}"
 HEAD_REVISION=`"${SVN_MERGE_SVN}" proplist --revprop -r HEAD "${HEAD_URL}" \
-  | grep '^Unversioned properties on revision' \
-  | sed 's/^Unversioned properties on revision \([0-9]\{1,\}\).*$/\1/g'`
+  | sed -e 's/.* \([0-9]\{1,\}\).*$/\1/g' -e 1q`
 if ! expr "${HEAD_REVISION}" : '[0-9]\{1,\}$' >/dev/null; then
     error "can't get head revision of \"${HEAD_URL}\" (got \"${REVISION}\")"
 fi
@@ -697,4 +741,3 @@ report latest revision of "${HEAD_URL}" is "${HEAD_REVISION}"
 
 # Perform action
 ${ACTION}
-
